### ISSUE TITLE
Derivatives of the riemann theta functions

### ISSUE THREAD

**Issue by wobau** [abelfunctions/abelfunctions#163]
How do I get information about the classes and methods defined in the package abelfunctions? In particular, I would like to compute partial derivatives up to the 4th order of the riemann theta functions.
Best regards
Wolfgang Bauhardt

**Comment by rparini** [comment]
Hi Wolfgang,
I'm afraid the documentation since the move from SymPy to Sage is not as comprehensive as I would like and while there are good docstrings in the code we're lacking a proper reference section of the documentation.

The specific answer to your question about derivatives is that you can provide directional derivatives as a list of lists using the `derivs` argument, in the same way as the `dirs` argument in [Maple](
https://www.maplesoft.com/support/help/maple/view.aspx?path=RiemannTheta).
So for example to repeat the examples in that Maple link with abelfunctions you could do
```python
from abelfunctions import RiemannTheta
import numpy as np

# define Riemann matrix
r3 = sqrt(-3)/3
B = np.array([[1+2*r3, -1-r3],
              [-1-r3, 1+2*r3]])

# evaluate RiemannTheta at the point z=[0, 1+i/10]
print(RiemannTheta([0, 1+1j/10], B))

# take the second order directional derivative in the directions 
# [1,0] and [0,1] at the point z=[0, 1]
print(RiemannTheta([0, 1], B, derivs=[[1,0], [0,1]]))
```
To take the fourth order directional derivative at the point [0, 1] in the direction [1,1] each time (i.e. apply the operator ([1,1].grad)^4 to the theta function)  you would do
```python
RiemannTheta([0, 1], B, derivs=[[1,1], [1,1], [1,1], [1,1]])
```
Hope that helps!

**Comment by wobau** [comment]
Hello Robert,
it works. Thank you very much for your quick help!
Wolfgang
