### ISSUE TITLE
Extension of abelfunctions - cyclepainter (custom paths)

### ISSUE THREAD

**Issue by markopuza** [abelfunctions/abelfunctions#168]
Hey everyone,

I would just like to point out that this exists. Cyclepainter is an extension to abelfunctions to define and manipulate custom paths on Riemann surfaces, with the final goal of calculating the Riemann matrix. I have programmed this as my bachelor thesis with @harrybraden. Is there any interest to integrate this within abelfunctions?

https://github.com/markopuza/abelfunctions-cyclepainter

The repo contains two non-trivial examples with Klein's curve and Bring's curve.

**Comment by rparini** [comment]
Hi Marko, I just had a quick play with this, looks very cool!  I've added a note on the Abelfunctions readme linking to it.

What would be your goal in integrating cyclepainter with abelfunctions?    

I would certainly welcome a PR that addressed #144 by allowing abelfunctions to use a custom cycle basis, perhaps defined as a list of (x,y) points on the riemann surface.  This would effectively move the path integration routines in cyclepainter into abelfunctions so that custom cycles made with cyclepainter could be used by abelfunctions to directly calculate things like the period matrix.

I'd be a bit more hesitant to include the GUI "cycle painting" functionality of cyclepainter directly in abelfunctions since it's so different from what abelfunctions currently offers and I think keeping them separate would make it easier for you to maintain/update that functionality.
