### ISSUE TITLE
Cythonized _find_int_points() has critical error, most likely memory leak

### ISSUE THREAD

**Issue by SartorisX** [abelfunctions/abelfunctions#68]

**Comment by SartorisX** [comment]
Looking at http://docs.cython.org/src/tutorial/array.html it seems possible that the issue might be directly using cpython.array.array as 
``` python
from cpython.array cimport array

cdef array stuff = array( 'i', [1, 2, 3])
```
rather than doing
```python
from cpython.array cimport array as c_array
from array import array

cdef c_array stuff = array( 'i', [1, 2, 3])
```

The latter should provide safe access to the array according to the above article.

**Comment by cswiercz** [comment]
I made these changes in ed9c59e5dbc2442953e6f908a3ecbc0512324703. However, I **occasionally** get some missing points, suggesting that there is still some sort of leakiness. Here's an example:

```python
# example Riemann matrix (from abelfunctions "Quick Tutorial")
Omega = numpy.array([[-1.309017+0.951057j, -0.809017+0.587785j],
                     [-0.809017+0.587785j, -1.000000+1.175571j]],
                    dtype=numpy.complex)
X = Omega.real
Y = Omega.imag
Yinv = numpy.linalg.inv(Y)
T = numpy.linalg.cholesky(Y)

# call _find_int_points(): possibly memory leak?
g = 2
R = 10.0
S = rt.integer_points._find_int_points(g,R,T)
S = numpy.array(S,dtype=numpy.int)
N = len(S)
S.resize((N/g,g))

plt.plot(S[:,0],S[:,1],'bo')
plt.axis('equal')
```

In some cases, the output plot looks like this:

![intpoints_error](https://cloud.githubusercontent.com/assets/915840/6944242/a8eedeec-d847-11e4-93f2-3ae8ab62f4c1.png)

In this case there is an int overflow. (As suggested by the axis limits.)

```python
print S
```
```
[[          0          -6]
 [         -3          -5]
 [         -4          -4]
 [         -5          -3]
 [-2147483648          -2]
 [         -6          -1]
 [         -6           0]
 [-2147483648           1]
 [         -5           2]
 [         -5           3]
 [         -4           4]
 [          0           5]
...
(the rest is omitted)
```

Here's another example where the output integer points doesn't really make sense:

```python
g = 2
R = 5.0    # <--- changed the radius to 5
S = rt.integer_points._find_int_points(g,R,T)
S = numpy.array(S,dtype=numpy.int)
N = len(S)
S.resize((N/g,g))

plt.plot(S[:,0],S[:,1],'bo')
plt.axis('equal')
```

![intpoints_error](https://cloud.githubusercontent.com/assets/915840/6944311/05887c3a-d848-11e4-81b5-a0028511804c.png)

Because I want to get the code in a position where you can work on more interesting things (like Siegel) I'll most likely revert to an older version of integer points for now. (Or a version that uses the deque you wrote. I couldn't find it in your older commits.)

Speaking of commits, the `theta_refactor` branch is where I'm keeping things.

**Comment by cswiercz** [comment]
@SartorisX Holy moly! I was reading [CRTF](http://www.ams.org/journals/mcom/2004-73-247/S0025-5718-03-01609-0/) again and saw that the Cholesky decomposition of **Y** is considered to be **upper triangular**, not lower triangular as is output by `numpy.linalg.cholesky`. The solution is to simply transpose. This gives the skewed picture I was expecting.
